MATRIX:
  SCREEN_WIDTH: 192
  SCREEN_HEIGHT: 96
  GPIO_SLOWDOWN: 3
  LED_COLS: 64
  LED_ROWS: 32
  GPIO_MAPPING: 'regular'
  CHAIN_LENGTH: 3
  PARALLEL: 3
SERVER:
  HOST: '192.168.1.73'
  PORT: 8080
DEFAULT_IMG: 'images/error.ppm'